/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCarousel: typeof import('element-plus/lib')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/lib')['ElCarouselItem']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/lib')['ElLoadingDirective']
  }
}
