/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElProgress: typeof import('element-plus/lib')['ElProgress']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElUpload: typeof import('element-plus/lib')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/lib')['ElLoadingDirective']
  }
}
