/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/panel copy 2.vue')['default']
    copy: typeof import('./src/components/panel4 copy.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Panel: typeof import('./src/components/panel.vue')['default']
    Panel2: typeof import('./src/components/panel2.vue')['default']
    Panel3: typeof import('./src/components/panel3.vue')['default']
    Panel4: typeof import('./src/components/panel4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
